/*
// This is the Application Controller generated by Play! when the project was created
package controllers;

import play.*;
import play.mvc.*;

import views.html.*;

public class Application extends Controller {

    public static Result index() {
        return ok(index.render("Your new application is ready."));
    }

}*/
package controllers;

import com.atlassian.connect.play.java.controllers.AcController;
import com.google.common.base.Supplier;
import play.mvc.Controller;
import play.mvc.Result;

/**
 * Application controller. Code given by Atlassian Connect from: http://localhost:9000/@connect/descriptor.
 *
 * Date: 28/01/14
 * Time: 11:14
 *
 * @author      Sav Balac
 * @version     1.0
 */
public class Application extends Controller {


    /**
     * Renders the Atlassian Connect module home page and returns the "descriptor" -
     * the contents of /atlassian-connect.json, currently set to "baseUrl": "http://localhost:9000".
     *
     * @return Result  The home page.
     */
    public static Result index() {
        return AcController.index(
                AcController.home(),    // The HTML home page from the module, as this is our documentation for now
                descriptorSupplier());  // Serve the descriptor when accept header is 'application/json'
                                        //     try 'curl -H "Accept: application/json" http://localhost:9000'
    }


    /**
     * Returns the "descriptor" -
     * the contents of /atlassian-connect.json, currently set to "baseUrl": "http://localhost:9000".
     *
     * @return Result  The descriptor as JSON.
     */
    public static Result descriptor() {
        return AcController.descriptor();
    }


    /**
     * Returns the "supplier".
     *
     * @return Supplier  The supplier.
     */
    private static Supplier descriptorSupplier() {
        return new Supplier() {
            public Result get() {
                return descriptor();
            }
        };
    }


}
